name: edriso
channels:
  - conda-forge
dependencies:
  - fastapi[all]==0.105.0
  - uvicorn[standard]==0.24.0.post1
  - xarray==2023.12.0
  - eccodes
  - cfgrib
  # - pynio==1.5.5
  - shapely==2.0.1
  - pip
  - pip:
    - edr-pydantic==0.2.1
    - covjson-pydantic==0.2.0