name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag edrisobaric:$(date +%s)
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: push docker image
      uses: fatjyc/push-gcr-action@v3.0
      with:
        run: |
          docker build . --tag ghcr.io/ways/store:latest
          docker push ghcr.io/ways/store:latest
